import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Terms of Use", description: "Terms governing your use of the Lately journaling app." };

export default function TermsPage() {
  return <LegalPage eyebrow="A fair agreement for using Lately" title="Terms of Use" updated="July 20, 2026">
    <p className="legal-lede">These Terms govern your use of the Lately mobile application and related website. By downloading, purchasing or using Lately, you agree to these Terms and, where applicable, Apple’s Licensed Application End User License Agreement.</p>
    <aside><strong>Please read these Terms carefully.</strong> If you do not agree, do not use Lately. Nothing in these Terms limits rights that cannot legally be limited under the consumer laws that apply to you.</aside>

    <h2>1. Who may use Lately</h2><p>You must be at least 13 years old and legally able to agree to these Terms. If local law requires a higher minimum age, that higher age applies. A parent or guardian must approve use where required.</p>
    <h2>2. Personal, lawful use</h2><p>Lately grants you a limited, personal, non-exclusive, non-transferable and revocable right to use the app on Apple devices you own or control, subject to Apple’s usage rules. You may not reverse engineer, resell, rent, disrupt, misuse or use Lately to violate law or another person’s rights.</p>
    <h2>3. Your memories</h2><p>You retain ownership of notes, photos and other content you place in Lately. You give us only the limited permission needed to process that content to operate features you request, including iCloud synchronization, speech transcription and AI recap generation. You are responsible for having the right to use content you add.</p>
    <h2>4. Subscriptions and purchases</h2><p>Lately may offer weekly or yearly auto-renewing subscriptions and a one-time lifetime purchase. The App Store purchase screen shows the current localized price, billing period and any introductory offer before you confirm payment. Any free trial applies only when explicitly displayed by Apple for your account.</p><p>Payment is charged to your Apple ID. Auto-renewing subscriptions renew unless cancelled at least 24 hours before the end of the current period. Apple manages billing, renewal, refunds and cancellation. You can manage or cancel a subscription in your Apple ID subscription settings. Deleting Lately does not cancel a subscription. Restore Purchases can restore eligible access associated with your Apple ID.</p>
    <h2>5. Lifetime access</h2><p>A “lifetime” purchase means access to the purchased Lately features for as long as we make the app commercially available and support that purchase on the relevant platform. It does not guarantee that every future feature or separate product will be included forever.</p>
    <h2>6. AI-generated recaps</h2><p>AI recaps may be incomplete, inaccurate or unexpected. They are intended for personal reflection and entertainment, not medical, psychological, legal, financial or other professional advice. Review outputs before relying on or sharing them.</p>
    <h2>7. Wellbeing and emergencies</h2><p>Lately is a journaling tool, not a healthcare provider, therapy service or emergency service. If you may harm yourself or someone else, contact local emergency services or an appropriate crisis service immediately.</p>
    <h2>8. Availability and changes</h2><p>We may improve, change, suspend or discontinue features to maintain security, comply with law or evolve the product. Some features depend on Apple, iCloud, Google Gemini, RevenueCat, internet access and device compatibility, and may be temporarily unavailable.</p>
    <h2>9. Updates</h2><p>You may need to install updates to continue using Lately safely. We are not responsible for problems caused by unsupported app or operating-system versions.</p>
    <h2>10. Disclaimer</h2><p>To the maximum extent permitted by law, Lately is provided “as is” and “as available.” We do not promise uninterrupted operation, permanent storage, or that AI output will be accurate. Keep appropriate backups and protect your Apple ID and device.</p>
    <h2>11. Limitation of liability</h2><p>To the maximum extent permitted by law, we will not be liable for indirect, incidental, special or consequential losses, lost memories, lost profits or loss of data arising from use of Lately. Our total liability relating to Lately will not exceed the greater of the amount you paid for Lately during the preceding 12 months or €50. These limits do not apply where prohibited by law or to liability that cannot legally be excluded.</p>
    <h2>12. Termination</h2><p>You may stop using Lately at any time. We may suspend access if you materially breach these Terms or use Lately unlawfully, where proportionate and legally permitted. Provisions that by their nature should survive termination will survive.</p>
    <h2>13. Apple-specific terms</h2><p>Apple is not responsible for maintaining or supporting Lately. To the extent Apple has any refund obligation under applicable law or its terms, you may notify Apple. Apple is a third-party beneficiary of these Terms and may enforce the Apple-specific provisions.</p>
    <h2>14. Governing law</h2><p>These Terms are governed by the laws of Lithuania, without depriving you of mandatory consumer protections in your country of residence. Courts with jurisdiction under applicable consumer law may hear disputes.</p>
    <h2>15. Changes and contact</h2><p>We may update these Terms and will post the revised date above. Material changes will receive notice where required. Questions can be sent to <a href="mailto:support@latelyapp.app">support@latelyapp.app</a>. Lately is operated by Daniel Nosevic in Lithuania.</p>
  </LegalPage>;
}
